<?php
/** @var Polushkin_TechTalk_Block_View $this */
?>

<h3 style="align-content: space-between; color: #00aa00">This is a db table 'contact'</h3>

<?php foreach ($this->getRequestedRecord() as $item) : ?>
    <div class="<?= $this->getData('class') ?>"><?php
            echo $item->getName() .  " said :" ."</br>";
            echo "<hr>";
            echo $item->getImage();
            echo $item->getComment() . "</br>"; ?>
    </div>
    <img src="<?= Mage::getBaseUrl('media') . 'blog' .DS. $item->getImage(); ?>" alt="Image">
<?php endforeach; ?>

<div>
    <?php $this->getChildChildHtml('cookies.notice') ?>
</div>
<div>
    <?php $this->getChildChildHtml('google.adress') ?>
</div>
<div>
    <?php echo $this->getChildHtml(‘topSearch’) ?>
</div>
<!--<img src="--><?//= $url = Mage::getBaseUrl('media') . 'blog' .DS. getImage();?><!--" alt="">-->