<?php
/**
 * @var Polushkin_Blog_Block_Post $this;
 */
?>
<?php $oneList = $this->getOneList();
      $oneCategoryList = $this->getOneCategorylist();
      $getImgUrl = Mage::getBaseUrl('media') . 'blog' .DS. $oneCategoryList->getImage();
?>

<div class="block" align="center">
    <div class="block-title" style="margin: 1%">
        <h1><?= $oneList->getName(); ?></h1>
    </div>
    <div class="item-container" style="margin: 1%">
        <p class="description"><?= $oneList->getContent();?></p>
    </div>
    <div class="block-image"><img src="<?= $getImgUrl ?>" alt="Image">
    </div>
</div>