<?php
/**
 * @var Polushkin_Blog_Block_View $this
 */
?>
<?php $oneList = $this->getOneList();
      $oneCategoryList = $this->getOneCategorylist();
      $getImgUrl = Mage::getBaseUrl('media') . 'blog' .DS. $oneCategoryList->getImage();
      $getRouteUrl = Mage::getUrl('*/index/post', ['post_id' => $oneCategoryList->getRequestId()])
?>

<div class="box-description" align="center" >
    <h1 style="border-radius: 10em/1em;"><?= $oneCategoryList->getName();?></h1>
    <p class="description"><?= $oneCategoryList->getDescription(); ?></p>
    <img src="<?= $getImgUrl; ?>"
         alt="the place for image but someone to steal it" style="background-color: grey; height="150px" width="150px">
    <ul class="block">
            <li><a href="<?= $getRouteUrl;?>">
                    <h3 style="margin: auto"><?= $oneList->getName(); ?></h3>
                    <p class="description"><?= $oneList->getShortDescription(); ?></p></a>
            </li>
    </ul>
    <div><?= $this->getPagerHtml(); ?></div>
</div>
